// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9N1poKoaDhD8Al1_GqkqJT4dDrxWSgcI',
    appId: '1:827582492974:web:fff93b186ae3a668c90abf',
    messagingSenderId: '827582492974',
    projectId: 'schoolpost-e5f75',
    authDomain: 'schoolpost-e5f75.firebaseapp.com',
    storageBucket: 'schoolpost-e5f75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLaH32UggY69RROw6ZMzbnMyHDM76NbAU',
    appId: '1:827582492974:android:e0cf50e484de1683c90abf',
    messagingSenderId: '827582492974',
    projectId: 'schoolpost-e5f75',
    storageBucket: 'schoolpost-e5f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1v2tfZUBcIB3OIOf9xuFqRL5MUYV0AQ',
    appId: '1:827582492974:ios:715b1581676609acc90abf',
    messagingSenderId: '827582492974',
    projectId: 'schoolpost-e5f75',
    storageBucket: 'schoolpost-e5f75.firebasestorage.app',
    iosBundleId: 'com.example.schoolPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1v2tfZUBcIB3OIOf9xuFqRL5MUYV0AQ',
    appId: '1:827582492974:ios:715b1581676609acc90abf',
    messagingSenderId: '827582492974',
    projectId: 'schoolpost-e5f75',
    storageBucket: 'schoolpost-e5f75.firebasestorage.app',
    iosBundleId: 'com.example.schoolPost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9N1poKoaDhD8Al1_GqkqJT4dDrxWSgcI',
    appId: '1:827582492974:web:e3e73b9c4148c18fc90abf',
    messagingSenderId: '827582492974',
    projectId: 'schoolpost-e5f75',
    authDomain: 'schoolpost-e5f75.firebaseapp.com',
    storageBucket: 'schoolpost-e5f75.firebasestorage.app',
  );
}
